Orientation:
        Kp: [ 50,50,50 ]
        Kd: [ .15,.15,.15]
        #Kp: [ 5.0,5.0,5.0 ]
        #Kd: [ .015,.015,.015 ]
        #Kp: [ 0,0,0 ]
        #Kd: [ 0,0,0 ]
Leg:
        Kp: 2 
        Kd: .02
        #Kp: 0
        #Kd: 0
SpringStiffness: 1000 # Not SO unreasonable that this is a parameter, as it is a soft contact simulator

Simulator:
  p0: [0,0,1]
  v0: [0,0,0]
  rpy0: [0,0,0]
  #w0: [10,10,10]
  w0: [0,0,0]
  pauseBeforeStart: 5 # in seconds
  speed: 1
  pert_force_x: [100, -100,100,-100]
  pert_force_y: [0,0, 100,100]
  #pert_force_x: [0, 00, 00]
  #pert_force_y: [0, 00, 00]
  pert_start: [3000, 8000, 11000,14000]
  pert_end: [3150, 8150, 11150, 14150]

Debug:
  dt: 0.001
  predHorizon: 1
  # using a predHorizon > 1 with torque is not good, as the torque will be changing
  stopIndex: 600000

MPC:
  N: 20
  stateScaling: [20,20,0,8,8,8,0,0,0,0, # pos
                 2.5,2.5,0,.03,.03,.03,0,0,0,0]   # vel
  inputScaling: [.01,.01,.01,.01]
  discountFactor: 1 # scale each future node by gamma^k
  terminalScaling: 1
  dt_flight: 0.01
  dt_ground: 0.001
  dt_replan: 0.01
  SQP_iter: 2
  tau_max: 15
  f_max: 0
  groundDuration: 0.07
  heightOffset: 0.35
  time_between_contacts: 0.3
  multiplier_on_deltaf: 0 # not SO unreasonable, as constraints are soft in Mujoco
  hop_height: 0.5
  circle_amp: -1
  circle_freq: 20
  max_vel: 5
